[project]
name = "blog-ronnyascencio-com"
version = "0.1.0"
description = "Blog project for personal webpage made with reflex "
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["reflex>=0.7.8"]
